### PR TITLE
For Evaluation: Hydra Houdini plugin

### PR DESCRIPTION
**Pull request by ablev-dwa**
### Description of Change(s)

This plugin draws gusd (ie USD Import) prims using Hydra, which is much faster, in particular animated USD is as fast as usdview.

See third_party/houdini/plugin/Hydra/README.md for more details about the implementation, features, and functionality.

### Note

We're looking for feedback and evaluation at this time. Please contact Bill Spitzak (bill.spitzak@dreamworks.com) and Alan Blevins (alan.blevins@dreamworks.com) with any comments or suggestions (or comment on this PR)

During this evaluation period, the **hydra_houdini_plugin** branch of the **dreamworksanimation** USD fork will be considered an active project, and we'll treat this as a separately-maintained plugin (that just happens to have everything you need to build natively with USD if you choose to merge it). If you'd like to help us develop this, get in touch and we'll set up a contributor agreement to merge changes to that branch.

### CODE REVIEW

**Comment by spitzak** [comment]
third_part/houdini/plugin/Hydra/README.md
<https://github.com/PixarAnimationStudios/USD/blob/e9e8e08ccd3215144bd13afbfcaf861d64500b5f/third_party/houdini/plugin/Hydra/README.md>

**Comment by spitzak** [comment]
I forgot to post the pretty picture:

[image: hydra_houdini_plugin.png]

**Comment by jtran56** [comment]
Filed as internal issue # USD-4707.

**Comment by spitzak** [comment]
New pull request here: https://github.com/PixarAnimationStudios/USD/pull/723

This is a small update with this patch
https://github.com/dreamworksanimation/USD/commit/8d12238862d7267c00bb310729c6690f0b156aaf
so that ROP usdoutput works.

Has anybody tried this out recently?

**Comment by c64kernal** [comment]
Thanks so much, @spitzak -- I'll go ahead an close this one out in favor of #723

**Pull request closed without merging**
