### PR TITLE
usdValidation: usdGeom: YUpAxisValidator

### PR DESCRIPTION
**Pull request by beersandrew**
### Description of Change(s)
- Moving the existing portion of the StageMetadataChecker from complianceChecker.py that verifies the upAxis is Y
- Added implementation code, a test, and necessary tokens & plugInfo entries

### Fixes Issue(s)
- https://github.com/orgs/PixarAnimationStudios/projects/3/views/1?pane=issue&itemId=65424791

Note: This PR is a replacement for https://github.com/PixarAnimationStudios/OpenUSD/pull/3399

### Checklist

[X] I have created this PR based on the dev branch

[X] I have followed the [coding conventions](https://openusd.org/release/api/_page__coding__guidelines.html)

[X] I have added unit tests that exercise this functionality (Reference: 
[testing guidelines](https://openusd.org/release/api/_page__testing__guidelines.html))

[X] I have verified that all unit tests pass with the proposed changes

[X] I have submitted a signed Contributor License Agreement (Reference: 
[Contributor License Agreement instructions](https://openusd.org/release/contributing_to_usd.html#contributor-license-agreement))

### CODE REVIEW

**Comment by jesschimein** [comment]
Filed as internal issue #USD-10491

**Review by tallytalwar — COMMENTED** [review]
Instead of doing a Up axis being Y check, I think this should be a stageMetadataValidator (https://github.com/PixarAnimationStudios/OpenUSD/blob/dev/pxr/usdValidation/usdValidation/coreValidators.cpp) which checks if a upAxis is authored or not and if not error on it.

As for up axis being "y" or not shouldn't be a  validator provided with openUSD. It seems from current compliance checker code that thats a arkit/scenekit requirement, and hence should also be part of suite of validators included in scenekit? cc. @dgovil

**Comment by beersandrew** [comment]
> Instead of doing a Up axis being Y check, I think this should be a stageMetadataValidator (https://github.com/PixarAnimationStudios/OpenUSD/blob/dev/pxr/usdValidation/usdValidation/coreValidators.cpp) which checks if a upAxis is authored or not and if not error on it.

This one is already covered [here](https://github.com/PixarAnimationStudios/OpenUSD/blob/dev/pxr/usdValidation/usdGeomValidators/validators.cpp#L41). Can this PR be closed?

**Comment by tallytalwar** [comment]
Yup I think so. Thanks @beersandrew

**Pull request closed without merging**
