### PR TITLE
Fix broken OpenEXR link in README

### PR DESCRIPTION
**Pull request by asluk**
Fix link to OpenEXR homepage.

### CODE REVIEW

**Comment by superfunc** [comment]
Hey @asluk,

I believe the relative links to the supported platforms section in dev have already been fixed. If you could update the PR to reflect that, I'd appreciate it.

**Comment by asluk** [comment]
Sure thing Josh; I've updated the PR to only refer to the broken OpenEXR link. Cheers~

**Comment by asluk** [comment]
Didn't mean to close this; had some mayhem in my local repo. Should be resolved now, but if it's easier, I can just remake the change in a fresh branch; it's just correcting the OpenEXR webpage.

**Comment by asluk** [comment]
nm; I'll remake the change in a fresh branch.

**Pull request closed without merging**
