### PR TITLE
[Build] Fix to allow script 'copyHeaderForBuild.py' to work with Python3 

### PR DESCRIPTION
**Pull request by phniix**
### Description of Change(s)
- Inserts brackets for print command around the Usage statement.
- Wrap script functionality into a `main()` function and execute under `if __name__ == '__main__':` .
- Add top level `sys.exit()` for appropriate program termination.
- Improve file content copy operation from src to dst.

### Fixes Issue(s)
- [605 - Build script, copyHeaderForBuild.py, fails when invoked with Python3 interpreter.](https://github.com/PixarAnimationStudios/USD/issues/605)

### CODE REVIEW

**Comment by jtran56** [comment]
Filed as internal issue #USD-4713.

**Comment by phniix** [comment]
@jtran56 Great stuff.

Where does that leave this PR ? Should I go ahead and kill it, or is it useful to keep open for you ?

Also, what's up with travis dying out on setup ?

```
2.94s$ sudo apt-get -qq update
W: http://ppa.launchpad.net/couchdb/stable/ubuntu/dists/trusty/Release.gpg: Signature by key 15866BAFD9BCC4F3C1E0DFC7D69548E1C17EAB57 uses weak digest algorithm (SHA1)
E: Failed to fetch http://us-central1.gce.archive.ubuntu.com/ubuntu/dists/trusty-updates/main/binary-i386/Packages  Writing more data than expected (1041450 > 1041449) [IP: 35.202.204.188 80]
E: Some index files failed to download. They have been ignored, or old ones used instead.
The command "sudo apt-get -qq update" failed and exited with 100 during .
Your build has been stopped.
```

Should I put in a ticket for that ?

**Comment by sunyab** [comment]
Hi @phniix, the internal issue is just for our own tracking, we do want to keep this PR open until we're able to look at it further. As for the Travis error, I think this is an intermittent error on their side. No need to put in an issue for that, I've restarted the build and hopefully it'll go through this time. Thanks!

**Comment by phniix** [comment]
@sunyab, thanks for clarifying what was meant by the internal issue comment. I now have a much better understanding on what was meant and how it relates to the workflow and process that is being used. I'll be sure keep this PR open and around. Fabulous! 

Good to know about the travis hiccup, and I can see that your restart has worked through nicely. One thing to enact, looking into the future, is to add a Python3 travis build environment. While the build phase passes, it doesn't appropriately verify this fix for a Python3 environment.

**Comment by sunyab** [comment]
I wouldn't say we support Python 3 either officially or even experimentally right now, at least not in our current master/dev branches. Internally, we haven't started looking at what code changes would be needed to get that support in place.

**Comment by sunyab** [comment]
Closing this pull request out in favor of #615. Thanks!

**Pull request closed without merging**
