### PR TITLE
multiverse support

### PR DESCRIPTION
**Pull request by asluk**
This is just to get the change to be reviewed by the Pixar folks, so they can see the actual code changes involved to get Multiverse support within the usdAbc plugin, as a CMake option. We've also discussed forking usdAbc with multiverse into its own standalone repo, to serve as a template for other developers writing SdfFileFormat plugins without needing to build the whole USD tree (e.g., on top of a brew install for USD on OSX, when that is available).

### CODE REVIEW

**Comment by spiffmon** [comment]
Aaron, would you like to modify your change to account for just-filed 
https://github.com/PixarAnimationStudios/USD/issues/70

Not sure what the right fix will be - guess it depends on whether the 
multiverse fork follows suit with the 1.5.8 release?

**Comment by asluk** [comment]
Yes, I can look at fixing that in a separate branch and then pulling it in.

As far as I can tell, the single-library Alembic was introduced in 1.6.0 -
https://github.com/alembic/alembic/commit/834eca66a05a06d45699600ce4bd724fe1c581b9

so I was thinking of using a version check to determine whether to look for
the single library or not, but I'm not sure if the same is true of the
Windows build for Alembic.

**Comment by asluk** [comment]
@spiffmon - multiverse is currently forked from an earlier version of alembic that does not produce the single library. I went ahead and added USD build support for the single alembic library in issue #70 , but that is independent of this change. For multiverse, there's one more cleanup I want to add  though (the boost_filesystem dependency that should be multiverse-specific). Thanks!

**Comment by spiffmon** [comment]
Thanks, Aaron - I was wondering about that dependency and why it was necessary... Can they not push it out of the header file, I wonder?

--SpiffiPhone

**Comment by asluk** [comment]
Should be fixed now-- only multiverse-enabled builds will bring in boost_filesystem.

**Comment by pberto** [comment]
> Thanks, Aaron - I was wondering about that dependency and why it was necessary... Can they not push it out of the header file, I wonder?

@spiffmon I sent you an e-mail mentioniong, along other things, that we need it to maintain the paths for the objects in the git repo of the multiverse abc files. Also we are now close to releasing 1.6.0+ (sinlgle lib) support, will be pushed soon (@panta). And big thanks to @asluk for the work.

**Comment by pberto** [comment]
@asluk FYI we have updated Multiverse to Alembic API 1.6.1 just now.

**Comment by asluk** [comment]
Thanks for the heads-up, @pberto . I tested with the panta/alembic-1.6.1-port branch and merged in my changes from my dev_abc_1_6_support into my dev_multiverse_support branch.

**Comment by pberto** [comment]
@asluk Alembic 1.7 port is also available now, branch: panta/alembic-1.7.0-port -- let us know.

**Comment by asluk** [comment]
@pberto  - I've verified that pulling https://github.com/PixarAnimationStudios/USD/pull/146 into this branch works with panta/alembic-1.7.0-port , and have made a separate pull request for the abc 1.7 fix as requested by Pixar folks. Cheers!

**Comment by pberto** [comment]
@asluk Awesome! Beers are on me. Cheers!

**Comment by sunyab** [comment]
I merged this pull request into the dev branch as commit f56da81, with some modifications so that it does not require USD to link directly to multiverse's dependencies. usdAbc must link to a shared library build of multiverse for now. Closing this out, thanks again @asluk!

**Pull request closed without merging**
