### PR TITLE
bug fix - added USD_API macro on UsdZipFileWriter rhs methods

### PR DESCRIPTION
**Pull request by philipheilmair**
### Description of Change(s)
Adding the USD_API macro to two rhs methods in zipFile.h, they were missing in the created dll for windows.

### Fixes Issue(s)
-USD_API added to methods in zipFile.h, line 235 and 236

### CODE REVIEW

**Comment by c64kernal** [comment]
Thanks so much @philipheilmair  -- have you had a chance to send in your CLA?  (Instructions here: http://graphics.pixar.com/usd/docs/Contributing-to-USD.html)  Appreciate the fix!

**Comment by philipheilmair** [comment]
No problem, I totally missed that part. I will sign and send it in immediately.

**Comment by c64kernal** [comment]
Thanks again!

**Comment by philipheilmair** [comment]
Waiting for an answer from my project leader regarding the CLA.

**Comment by jilliene** [comment]
Filed as internal issue #USD-5349

**Comment by philipheilmair** [comment]
Hey, short update from me; This CLA has to go through our legal department, I am afraid that it will take some time until I can send it.
It is perhaps faster to solve it internally.

**Comment by c64kernal** [comment]
No problem at all, we'll get it taken care of internally.  Thanks again for calling it out.

**Pull request closed without merging**
