### PR TITLE
Autodesk: Support 3d texture from a sdr node with test case

### PR DESCRIPTION
**Pull request by erikaharrison-adsk**
### Description of Change(s)

Currently only 2D textures can be linked in a UsdShadeMaterial node by using a UsdShadeShader node with type 'UsdUVTexture'. This PR adds a new type, Texture3D, in Sdr node role ([link](https://github.com/PixarAnimationStudios/OpenUSD/blob/0ecb5dd70287846d16e8058e9aedbf6b47fb5230/pxr/usd/sdr/shaderNode.h#L75)), to add the new ability to connect a 3D texture in a UsdShadeMaterial.
With this ability, users can freely define customized Shader plugin to link a 3d texture in the final material, and also a surface shader to sample from the 3d texture. An example is provided in the unit test.
Check [usd-interest group](https://groups.google.com/g/usd-interest/c/OtSRGFUWw-U) for prior discussion.

### Fixes Issue(s)
- N/A

- [X] I have verified that all unit tests pass with the proposed changes

- [X] I have submitted a signed Contributor License Agreement

### CODE REVIEW

**Comment by jesschimein** [comment]
Filed as internal issue #USD-8916

**Comment by erikaharrison-adsk** [comment]
Hi @jesschimein or is there another person I should tag? Any update on this PR? We've a shipping product that's looking to incorporate this work. Let us know if there's anything on our end we can do to help this along. Maybe we can get some feedback before addressing the new merge conflict?

**Comment by jesschimein** [comment]
Hey @erikaharrison-adsk!  Checking with the team, we think 3d texture is something that might be better facilitated through MaterialX rather than UsdPreviewSurface.  There's a [good conversation in the ASWF MaterialX Slack](https://academysoftwarefdn.slack.com/archives/C0230LWBE2X/p1709336008196439?thread_ts=1682311529.421589&cid=C0230LWBE2X) where we'd love to get your team's thoughts.  Would it be possible to have some folks from Autodesk weigh in there?

**Comment by erikaharrison-adsk** [comment]
Closing this PR as we're going to look at an alternative approach likely harnessing MaterialX.

**Pull request closed without merging**
