### PR TITLE
UsdPhysics schema

### PR DESCRIPTION
**Pull request by AlesBorovicka**
### Description of Change(s)
Adding UsdPhysics schema based on the proposal https://graphics.pixar.com/usd/docs/Rigid-Body-Physics-in-USD-Proposal.html
### Fixes Issue(s)
-

### CODE REVIEW

**Comment by jilliene** [comment]
Filed as internal issue #USD-6535

**Comment by dgovil** [comment]
Hi all, just wondering if there were any updates on this PR? I hadn't seen any major changes to the upstream branch, and was just curious.

Cheers

**Comment by spiffmon** [comment]
Hi @dgovil , we had taken some time to explore some related/future-looking issues to see if they would behoove any changes to the proposed schema.  That process has wound down, and the PR is in review - you can expect to see it in 21.08.

**Comment by dgovil** [comment]
Awesome, thanks for the update Spiff. Looking forward to seeing this!

**Comment by AlesBorovicka** [comment]
Updated few documentation strings

**Pull request merged**
