### PR TITLE
UsdMtlx: Support for resolving file prefixes defined in parent tags

### PR DESCRIPTION
**Pull request by willmuto-lucasfilm**
### Description of Change(s)

UsdMtlx will now correctly resolve filenames with a prefix defined with the fileprefix attribute in a parent tag.

### Fixes Issue(s)

Issue #974 usdMtlx ignores an active file prefix

### CODE REVIEW

**Comment by jilliene** [comment]
Filed as internal issue #USD-5577

**Comment by c64kernal** [comment]
Hi @willmuto-lucasfilm -- we don't have a record of your name on the corporate CLA, please follow up on your end to get added to the corporate CLA we have on file -- and thanks for the PR!

**Comment by willmuto-lucasfilm** [comment]
Sure thing, @c64kernal ! I'm looking into this now.

**Comment by willmuto-lucasfilm** [comment]
Hi @c64kernal , I chatted with leadership and it sounds like things are sorted on my end. Let me know if you need additional information!

**Comment by willmuto-lucasfilm** [comment]
Closing this pull request to rebase against `dev`.

**Pull request closed without merging**
