### PR TITLE
[Build] Only build boost bits required for OIIO when building OIIO.

### PR DESCRIPTION
**Pull request by superfunc**
### Description of Change(s)
This dependency was removed, so we don't need to build a shared
library or install its headers in the build script anymore.

### Fixes Issue(s)
- None filed.

### CODE REVIEW

**Comment by superfunc** [comment]
Hey G :) 

I'm not sure, thanks for bringing it up, I'll run it through an oiio build.

**Comment by superfunc** [comment]
@c64kernal You were right, amended the PR to do it conditionally, thanks for spotting it.

**Comment by c64kernal** [comment]
Thanks Josh!  We might want to do the same with date_time while we're at it...

**Comment by superfunc** [comment]
Yeah that seems reasonable, added as a separate commit.

**Comment by c64kernal** [comment]
Thanks @superfunc!

**Comment by c64kernal** [comment]
@superfunc -- the latest dev branch should have all this functionality merged in (in some form or another) I'll close this out, but if there's more you're missing, please let me know!

**Pull request closed without merging**
