### PR TITLE
Apple: Upgrade MaterialX to 1.38.8

### PR DESCRIPTION
**Pull request by dgovil**
### Description of Change(s)

This PR upgrades MaterialX to 1.38.8. [CHANGELOG](https://github.com/AcademySoftwareFoundation/MaterialX/blob/main/CHANGELOG.md#1388---2023-09-08)

The big upgrade for us is the support for iOS builds and DisplayP3 support, but there are a ton of great changes in that ChangeLog

- [X] I have verified that all unit tests pass with the proposed changes

- [X] I have submitted a signed Contributor License Agreement

### CODE REVIEW

**Comment by jesschimein** [comment]
Filed as internal issue #USD-9315

**Comment by dgovil** [comment]
@spiffmon I realize that MaterialX 1.38.9 just came out https://github.com/AcademySoftwareFoundation/MaterialX/releases/tag/v1.38.9

The biggest changes that might be beneficial over 1.38.8 is some correctness fixes to the nodes. I didn't want to assume that was fine for y'all, but thought I'd mention it here in case you want to skip forward.

**Comment by spiffmon** [comment]
Closing, as we _are_ going to go directly to 1.38.9, and handling the upgrade internally.  Thanks, @dgovil !

**Comment by dgovil** [comment]
@spiffmon  FYI, you'll probably need this patch for macOS unless MaterialX releases a 1.38.10 with it

https://github.com/AcademySoftwareFoundation/MaterialX/pull/1741

**Comment by spiffmon** [comment]
@dgovil , since we don't do XCode builds in our internal builds, we didn't think we'd be affected?

**Comment by dgovil** [comment]
Hmm I don't think it's specific to Xcode. I'm building with Ninja and get these build errors. 

It fails at the cmake step because it's looking up the MaterialX cmake exported config , but it has an invalid linker string exported out.

**Comment by spiffmon** [comment]
OK, I reckon we'll sort it then - thanks!

**Pull request closed without merging**
