### PR TITLE
Add maya 2018 and 2019 in findmaya.cmake for Win

### PR DESCRIPTION
**Pull request by devGitHub48**
### Description of Change(s)
Add the version of Maya to be able to compile correctly
### Fixes Issue(s)
- not being able to compile with Maya 2018 and 2019

### CODE REVIEW

**Comment by devGitHub48** [comment]
I wasn't able to test on others platform that Windows. So I haven't changed these. Feel free to change them!

**Comment by jtran56** [comment]
Filed as internal issue #163148.

**Comment by sunyab** [comment]
2140815f0d0bc56c2e0b455d5baea2b0415c916e recently landed in the dev branch and adds support for Maya 2018 and 2019 on macOS/Linux/Windows, so I'm going to close out this PR in favor of that commit. Thanks @devGitHub48!

**Comment by devGitHub48** [comment]
Thanks a lot for the follow up!

**Pull request closed without merging**
