### PR TITLE
Remove 'usd_' prefix for monolithic build.

### PR DESCRIPTION
**Pull request by SGoetschi**
A monolithic build will result in usd_usd_ms.dll or libusd_usd_ms.so resp.
By removing the 'usd_' prefix from the 'ms' target we only get the 'usd_'
prefix from PXR_LIB_PREFIX instead of the repeated 'usd_usd_'.

### CODE REVIEW

**Comment by sunyab** [comment]
Hi @SGoetschi, thank you for this PR! We need a signed CLA from contributors before we're able to merge their changes into the repository, could you please follow the instructions at https://graphics.pixar.com/usd/release/contributing_to_usd.html? Once we receive the CLA we'll be able to move forward. Thanks!

**Comment by jilliene** [comment]
Filed as internal issue #USD-7075

**Comment by FlorianZ** [comment]
@SGoetschi , just wondering if you had a chance to submit the completed CLA form? Just double-checking that we are not missing anything from our end. Thank you!

**Comment by SGoetschi** [comment]
Hi @FlorianZ I've been bugging our Legal department for some time now. I'm still trying to get the CLA signed. Sorry for the delay.

**Comment by SGoetschi** [comment]
I just handed in the signed CLA. So I expect this issue to be unblocked within a couple of days.
Thanks for your patience.

**Comment by SGoetschi** [comment]
@FlorianZ Did you hear anything from your legal department regarding my CLA?
I handed the CLA and my username in and didn't hear anything back (even after asking again).

**Comment by sunyab** [comment]
Hi @SGoetschi, sorry for the late response. Yes, we did receive your CLA and we'll looking to merge your PR shortly. Thanks for your patience!

**Comment by sunyab** [comment]
Apologies for not posting sooner -- while reviewing this PR we decided to go with a different route to fixing it that seemed simpler and required less changes. That commit (626dfa1) is in the dev branch now. I'm going to close this out, thanks!

**Pull request closed without merging**
