### PR TITLE
Apple: Fixes for stricter compiler parsing

### PR DESCRIPTION
**Pull request by dgovil**
### Description of Change(s)

An upcoming Clang/LLVM version has stricter mandatory template checking that causes OpenUSD to fail to compile.
These are technically issues in the OpenUSD codebase that go against the C++ standard, but compilers have ignored them thus far. Therefore I am submitting them as fixes here.

We request that these please be part of the 25.2 release to prevent compilation issues for other developers.

The two issues:

1. Clang will check for template uses along uninitialized paths as well during compilation. `SdfChildrenProxy` had one such path, which had to be removed to allow compilation as it referenced a non existent method.
See the [changelog](https://releases.llvm.org/19.1.0/tools/clang/docs/ReleaseNotes.html#improvements-to-clang-s-diagnostics:~:text=Clang%20now%20looks%20up%20members%20of%20the%20current%20instantiation%20in%20the%20template%20definition%20context%20if%20the%20current%20instantiation%20has%20no%20dependent%20base%20classes.) and [PR](https://github.com/llvm/llvm-project/pull/84050)
2. Clang is being stricter about templated function calls in its parser. `Sdf_Children<ChildPolicy>::_UpdateChildNames()` used a method call that was in violation of the following ISO spec:

   ISO C++03 14.2/4:

   > When the name of a member template specialization appears after . or -> in a postfix-expression, or after nested-name-specifier in a qualified-id, and the postfix-expression or qualified-id explicitly depends on a template-parameter (14.6.2), the member template name must be prefixed by the keyword template. Otherwise the name is assumed to name a non-template.

    Explicitly adding the template keyword resolves this. Unfortunately this also gets tagged as unnecessary by older LLVM versions or other compilers. However, a warning felt better than a compile failure.

### Checklist

[X] I have created this PR based on the dev branch

[X] I have followed the [coding conventions](https://openusd.org/release/api/_page__coding__guidelines.html)

[ ] I have added unit tests that exercise this functionality (Reference: 
[testing guidelines](https://openusd.org/release/api/_page__testing__guidelines.html))

[X] I have verified that all unit tests pass with the proposed changes

[X] I have submitted a signed Contributor License Agreement (Reference: 
[Contributor License Agreement instructions](https://openusd.org/release/contributing_to_usd.html#contributor-license-agreement))

### CODE REVIEW

**Comment by jesschimein** [comment]
Filed as internal issue #USD-10458

**Comment by nvmkuruc** [comment]
Just to confirm @dgovil -- You're saying that because `SdfChildrenProxy` doesn't have a `_Set` method, the assignment operator can never be initialized?

```
_owner->_Set(*_pos, x);
```

The change looks good to me, but I'm just making sure I understand which method was non-existent.

**Comment by dgovil** [comment]
@nvmkuruc  Yes, pretty much. In older versions of the compiler, that path would never be taken and so the compiler never discovers that `_Set` isn't locatable. 

However, now it traverses paths that aren't used as a safety measure, and sees that there's no way to find `_Set`, and so fails to compile.

**Comment by dgovil** [comment]
Just to flag it here, once this PR is merged, folks will also hit a similar issue if they enable VDB during the build.
I have submitted a PR to VDB as well at https://github.com/AcademySoftwareFoundation/openvdb/pull/1977 and then we can figure out how to address the build_usd.py version accordingly.

**Comment by mont29** [comment]
Can confirm that this PR fixes the issue I have when building Blender with clang19 on linux (reported as #3442).

**Comment by dgovil** [comment]
My changes in OpenVDB 12 have landed. I will see if it's possible to get a new tag cut from them.
I've tested this PR against my patch for OpenVDB and they both compile fine together.

**Comment by sunyab** [comment]
Just noting this change has been merged internally and will be part of the next dev push.

**Comment by dgovil** [comment]
Awesome. Thanks for fast tracking that, Sunya. I'll close this out when that lands.

**Pull request merged**
