### PR TITLE
Lo fi

### PR DESCRIPTION
**Pull request by benmalartre**

### CODE REVIEW

**Comment by jesschimein** [comment]
Filed as internal issue #USD-10213

**Comment by spiffmon** [comment]
Hi @benmalartre , this looks like an impressive body of work!  However, we regretfully need to close this PR because it _is_ such a substantial set of feature additions to USD that **must** be submitted, reviewed, and discussed (as a set of, given the multiple features it contains) on https://github.com/PixarAnimationStudios/OpenUSD-proposals before considering an implementation.

Moreover, the direction of basing core USD execution behavior on top of Ndr networks is not the direction we intend to pursue for OpenExec, the core execution framework.

Again, this is fantastic work to see, but we'd suggest it needs to be formulated as a set of plugins rather than as additions to OpenUSD-core, but if there are smaller "enabling" changes needed inside the core to facilitate publishing such plugins yourself, we'd be happy to consider those changes.

Finally, we have on our roadmap to deprecate and remove Ndr, leaving only Sdr with the full functionality of Ndr "pulled up" into it.

Cheers and keep up the great work!

**Comment by benmalartre** [comment]
This was not my intention that the PR came to you ! Thanks for the message ans closing it!!!

Regards,
Ben

Téléchargez Outlook pour iOS<https://aka.ms/o0ukef>
________________________________
De : F. Sebastian (spiff) Grassia ***@***.***>
Envoyé : Monday, September 30, 2024 11:45:38 PM
À : PixarAnimationStudios/OpenUSD ***@***.***>
Cc : benjamin malartre ***@***.***>; Mention ***@***.***>
Objet : Re: [PixarAnimationStudios/OpenUSD] Lo fi (PR #3329)


Hi @benmalartre<https://github.com/benmalartre> , this looks like an impressive body of work! However, we regretfully need to close this PR because it is such a substantial set of feature additions to USD that must be submitted, reviewed, and discussed (as a set of, given the multiple features it contains) on https://github.com/PixarAnimationStudios/OpenUSD-proposals before considering an implementation.

Moreover, the direction of basing core USD execution behavior on top of Ndr networks is not the direction we intend to pursue for OpenExec, the core execution framework.

Again, this is fantastic work to see, but we'd suggest it needs to be formulated as a set of plugins rather than as additions to OpenUSD-core, but if there are smaller "enabling" changes needed inside the core to facilitate publishing such plugins yourself, we'd be happy to consider those changes.

Finally, we have on our roadmap to deprecate and remove Ndr, leaving only Sdr with the full functionality of Ndr "pulled up" into it.

Cheers and keep up the great work!

**Pull request closed without merging**
