### PR TITLE
[build_usd] Use secure https where possible when downloading packages

### PR DESCRIPTION
**Pull request by WD-stefaang**
### Description of Change(s)

Added https where possible to download the dependencies. Seems like www.ijg.org doesn't support it.

### Fixes Issue(s)
-

### CODE REVIEW

**Comment by jtran56** [comment]
Filed as internal issue #USD-4822.

**Comment by sunyab** [comment]
Hi @WD-stefaang, thanks for the pull request! We ask all contributors to sign a CLA with us; you can find instructions for this here: https://graphics.pixar.com/usd/docs/Contributing-to-USD.html

Once we receive your CLA we can take a look at the change and get it merged in. Thanks!

**Comment by WD-stefaang** [comment]
FYI, I'm waiting for a heads up from the legal team to be in the clear.

**Comment by sunyab** [comment]
I've merged this change internally and it'll be included in the next push. I made some small modifications:

- I tried the ijg.org download with https and it seemed to work OK, so I added that in.
- I reverted the links to graphics.pixar.com back to openusd.org. We prefer to use that URL for user-facing docs and instructions.

Please let me know if there are any issues with these changes. Thanks!

**Comment by WD-stefaang** [comment]
Sure, looks good!

**Pull request merged**
