### PR TITLE
Fix for DLL export import mismatch

### PR DESCRIPTION
**Pull request by aaye**
### Description of Change(s)
- Fix some API tagging so that source and header have matching dll import export states.

### Fixes Issue(s)
- Fix compiler warnings.

- [ ] I have verified that all unit tests pass with the proposed changes

- [ x] I have submitted a signed Contributor License Agreement

### CODE REVIEW

**Comment by jesschimein** [comment]
Filed as internal issue #USD-8706

**Comment by spiffmon** [comment]
Would you mind updating/resolving this, @aaye ?  All but the usdSkelImaging and usdVolImaging have been resolved, but we'd love to get your fixes for those two!

**Comment by aaye** [comment]
Happy to but it will take me a bit. Have not updated/pulled down the repo for a few months.

**Comment by tcauchois** [comment]
Hey Andrew,

I've merged the remaining fixes from your PR, and will check it in early next week if CI is clean (which it should be).  No need for you to do the merge.

Thanks!
Tom

**Pull request merged**
