### PR TITLE
Replace `boost::bad_get` with new exception type

### PR DESCRIPTION
**Pull request by nvmkuruc**
### Description of Change(s)

(Requires #3005)

`boost::variant` is no longer used in OpenUSD. Its associated exception `boost::bad_get` is being used to signal that a conversion error has occurred during the parse.  This replaces usage of `boost::bad_get` with a new exception type `ConversionError` and removes the last non-python usage of boost in `sdf`.

### Fixes Issue(s)
-

- [ ] I have verified that all unit tests pass with the proposed changes

- [x] I have submitted a signed Contributor License Agreement

### CODE REVIEW

**Comment by jesschimein** [comment]
Filed as internal issue #USD-9506

**Comment by spiffmon** [comment]
THanks, @nvmkuruc !  It turns out Alex had a change already sitting in his tree that deboostifies the existing sdf parser code, so we'll get that in ASAP, and plan on pulling this in after we've moved to PEGTL.  Not sure if our change will cause conflicts for yours.

**Comment by nvmkuruc** [comment]
We'll just adapt the PEGTL change whenever you do the next dev push.

**Pull request closed without merging**
