### PR TITLE
PEGTL USDA Parser

### PR DESCRIPTION
**Pull request by erslavin**
- Added additional text file format parser based on PEGTL
- Added tests specific to PEGTL parser
- Removed lex / yacc based parser

### Description of Change(s)

This change introduces a new sdf / usda text file format paser based on PEGTL.  This change aligns the way text file scene descriptions are parsed with the way paths are now being parsed and removes the need for a dependency on lex / yacc.

Added PEGTL Text File Format Parser
Added tests specific to PEGTL parser that allow testing of partial scene description rules

### Fixes Issue(s)
-

- [X] I have verified that all unit tests pass with the proposed changes

- [X] I have submitted a signed Contributor License Agreement

### CODE REVIEW

**Comment by asluk** [comment]
Conflicts will be resolved next week 🙏🏼

**Comment by jesschimein** [comment]
Filed as internal issue #USD-9462

:heavy_exclamation_mark: Please make sure that a signed CLA has been submitted!

**Comment by jesschimein** [comment]
Please disregard the missing CLA comment -- we have it on file!

**Comment by nvmkuruc** [comment]
There's a bug right now and the parser won't handle CPP Multiline comments not separated by whitespace.  We'll update the pull request when a fix has been pushed and include a test to cover this case.
```
/*HELLO*//*WORLD*/
```

**Comment by tallytalwar** [comment]
Just noting that, I have internally resolved the conflict which occurred with a38c32c66a8b3e920e7fe0d13d1d3b3879a67f88 change, so don't worry about rebasing this PR :D.

**Pull request merged**
