### PR TITLE
[hdEmbree][build_usd] add to build_usd.py status message (standalone)

### PR DESCRIPTION
**Pull request by pmolodo**
> [!IMPORTANT] 
> This is a duplicate of this PR:
>
> - https://github.com/PixarAnimationStudios/OpenUSD/pull/3234
>
> ...except pulled out the UsdLux-HdEmbree PR "chain", to make for easier standalone integration, as it has no other PR dependencies, and is a simple/small change.
>
> I will close this PR if the other is merged first, and vice-versa.

### Description of Change(s)

Add hdEmbree to build_usd.py status message

- [X] I have verified that all unit tests pass with the proposed changes

- [X] I have submitted a signed Contributor License Agreement

### CODE REVIEW

**Comment by jesschimein** [comment]
Filed as internal issue #USD-9994

**Comment by pmolodo** [comment]
Closing, as https://github.com/PixarAnimationStudios/OpenUSD/pull/3234 was rebased, and is now standalone vs dev

**Comment by pmolodo** [comment]
Closing, as https://github.com/PixarAnimationStudios/OpenUSD/pull/3234 was rebased, and is now standalone vs dev

**Pull request closed without merging**
