### PR TITLE
fix URL link - capitalization counts in this one

### LINKED ISSUE #7: invalid public link in the readme
https://github.com/PixarAnimationStudios/USD/blame/master/README.md#L22:

`http://openusd.org/docs/Getting-Help-With-USD.html` is resolving to http://graphics.pixar.com/usd/docs/Getting-Help-With-USD.html, and that's returning a 404.

### PR DESCRIPTION
**Pull request by heckj**
resolves #7 - found appropriate reference in http://graphics.pixar.com/usd/docs/

### CODE REVIEW

**Comment by sunyab** [comment]
Thanks for filing our very first pull request! We ask that all contributors fill in a contributor license agreement (CLA) and send it to us before we merge changes in. You can find the instructions for filling out the form and submitting it here: http://graphics.pixar.com/usd/docs/Contributing-to-USD.html

Sorry for the trouble, and thanks again!

**Comment by heckj** [comment]
ah, gotcha @sunyab - will fill it out as soon as I can get to a printer and make a physical signature and send it in.

**Comment by heckj** [comment]
@sunyab CLA should be in your system now

**Comment by sunyab** [comment]
@heckj: I'll double check that we received and processed your CLA. One last thing: could you please retarget your pull request to the 'dev' branch instead of 'master'? Per this [issue](https://github.com/isaacs/github/issues/18), I think you might have to file a new pull request to do this. Thanks!

**Comment by heckj** [comment]
@sunyab yeah - no problem. I'd recommend adding a note to that effect in your README/contribution guide if you expect that though - either that or set the "default" branch in the repository to "dev", which should make it default to PRs to that branch

**Comment by heckj** [comment]
closing this in favor of https://github.com/PixarAnimationStudios/USD/pull/14

**Pull request closed without merging**
