### PR TITLE
 EMSUSD-1691 - Load mono EXR images

### PR DESCRIPTION
**Pull request by seando-adsk**
### Description of Change(s)
Load mono EXR images
### Fixes Issue(s)
- #3289 

- [ ] I have verified that all unit tests pass with the proposed changes

- [x] I have submitted a signed Contributor License Agreement

### CODE REVIEW

**Comment by jesschimein** [comment]
Filed as internal issue #USD-10243

:heavy_exclamation_mark: Please make sure that a signed CLA has been submitted!

**Comment by seando-adsk** [comment]
@jesschimein I should be covered under CLA (from a long time ago) from Autodesk.

**Comment by jesschimein** [comment]
Yes, I've got you on the CLA!  Sorry for the confusion; we updated our CLA checking system a bit recently and have some truing up to do in our records.  Thanks for the note!

**Pull request merged**
