### PR TITLE
fix: export targets for usd_ms correctly

### PR DESCRIPTION
**Pull request by sssooonnnggg**
### Description of Change(s)
Currently the pxrTargets.cmake for  monolithic buid is missing, and pxrConfig.cmake is broken.

### Fixes Issue(s)
- #1088

- [x] I have submitted a signed Contributor License Agreement

### CODE REVIEW

**Comment by slingthor** [comment]
We were looking at this as well! Really would like to see this included

**Comment by tallytalwar** [comment]
Filed as internal issue #USD-7615

**Comment by tallytalwar** [comment]
Hi @sssooonnnggg 

Thanks for the PR, this mostly looks good to us and in order to bring it in and test it, we require a CLA to be signed. 

It seems we do not have a CLA on record for you, could you please follow the instructions here: https://graphics.pixar.com/usd/release/contributing_to_usd.html#contributor-license-agreement?

**Comment by sssooonnnggg** [comment]
@tallytalwar 
Thanks for reviewing, I have sent a signed CLA to usd-cla@pixar.com a few minutes ago.

**Comment by sssooonnnggg** [comment]
@tallytalwar 

It seems that my signed CLA has been accepted by Pixar, so this PR can be merged :)

**Comment by tallytalwar** [comment]
Yup, thanks @sssooonnnggg . Aiming to include it in our next dev branch push.

**Pull request merged**
