### PR TITLE
Fix spelling: indicies -> indices

### PR DESCRIPTION
**Pull request by Vertexwahn**
### Fixes Issue(s)
-

- [ ] I have verified that all unit tests pass with the proposed changes

- [ ] I have submitted a signed Contributor License Agreement

### CODE REVIEW

**Comment by tallytalwar** [comment]
Filed as internal issue #USD-8285

**Comment by FlorianZ** [comment]
Hi @Vertexwahn, would you mind please providing a description for your PR and supplying information on which version of boost python introduced the get_indices method?
Also, if you wouldn't mind please reverting the .vscode configuration file that inadvertently slipped into this PR?
Thank you!!

**Comment by Vertexwahn** [comment]
Sorry - didn't get that this is a boost Python binding thing. Was thinking this is a typo - just checked Boost 1.82.0 - it is still called `get_indicies` - sorry for the confusion

**Comment by FlorianZ** [comment]
@Vertexwahn, no you're certainly on to something. I believe this is actually a typo in boost. They later corrected it by adding the `get_indices` API alongside the misspelled `get_indicies`. Both methods do the same thing - one just calls into the other. We can certainly fix this by accepting a PR that calls the correctly spelled method, but we need to be careful to make sure we're not breaking backwards compatibility with any older versions of boost that we still support. I don't know which version of boost introduced the corrected spelling.

**Pull request closed without merging**
