### PR TITLE
[usdGenSchema] Added --headerTerminatorString optional argument.

### PR DESCRIPTION
**Pull request by moddyz**
### Description of Change(s)

Added `--headerTerminatorString` as an optional command-line argument to `usdGenSchema`.

This enables developers to customize the otherwise hard-coded `#endif` string which terminates the generated header files.  The use-case outlined in #1092 was for supporting developers intending to use `#pragma once` as the header guarding mechanism.

The default value of the `--headerTerminatorString` argument is `#endif` to preserve old behavior.  

### Fixes Issue(s)
- #1092

### CODE REVIEW

**Comment by moddyz** [comment]
@spiffmon I know we discussed on @1092 that it would be also useful to a companion argument which can customize the "Close the include guard with #endif" comment.  

It looks like those comments are encoded in the [schemaClass.h template](https://github.com/PixarAnimationStudios/USD/blob/dev/pxr/usd/usd/codegenTemplates/schemaClass.h#L401)  already so the argument won't be necessary!

**Comment by spiffmon** [comment]
Ah, of course, @moddyz - thanks!

**Comment by spiffmon** [comment]
Change looks great, @moddyz - we'll try to get it in soon!

**Comment by jilliene** [comment]
Filed as internal issue #USD-5820

**Pull request merged**
