### PR TITLE
Fix UsdFlattenLayerStack to handle time sampled asset paths

### PR DESCRIPTION
**Pull request by marktucker**
### Description of Change(s)

Add code to handle time sampled asset paths or arrays of asset paths when
flattening a layer stack. This complements the existing code for fixing
single asset paths or arrays of asset paths.

### Fixes Issue(s)
- #1168

### CODE REVIEW

**Comment by jilliene** [comment]
Filed as internal issue #USD-6003

**Comment by c64kernal** [comment]
Thanks for this @marktucker -- would it be possible to get a test for this? You can potentially augment an existing test hopefully to make it easier. You don't have to amend this PR, we're getting ready to merge it, so if you're up for adding the test, getting a different PR for that would be awesome.

Thanks again! Really appreciate it.

**Comment by marktucker** [comment]
Yep, I think I can turn the sample files from #1168 into a test. I'll put the test in a separate PR.

**Comment by c64kernal** [comment]
That's perfect, thank you so much Mark!

**Comment by spiffmon** [comment]
Hi @marktucker ,
   Apologies for slowness on getting you review comments.  Here they are:

1. I think we can iterate references in a std::map in C++-11, so why introduce a first use of TF_FOR_ALL in this file when a range-based for should do?  We are (long term) trying to deprecate TF_FOR_ALL.
2. We now have two different chunks of duplicated code in this function.. granted it's all reasonably colocated, but could we make two nice little lambda's to share?
3. Not sure how big an actual performance difference it would make, but I'd invert the loop ordering of timeSamples and value-type-checks, which would avoid an IsHolding() call for each timeSample.... if the timeSamples aren't of uniform type, we have much bigger problems.

With these changes, it might be nice to also fold the unit test into the same PR?

Cheers,
@spiffmon

**Comment by marktucker** [comment]
Thanks for the suggestions. I have implemented these changes, and added the unit test in a new commit on this branch.

**Pull request merged**
