### PR TITLE
Linux arm64 support.

### PR DESCRIPTION
**Pull request by tsahee**
### Description of Change(s)
This change adds support for arm64/linux.
Currently, arm64 is only supported for OSX.

### Fixes Issue(s)
Fixed compilation errors caused trying to compile intel-architecture assembly on arm64.

### CODE REVIEW

**Comment by jilliene** [comment]
Filed as internal issue #USD-6573

**Comment by AGSaidi** [comment]
I'd love to see this merged.

**Comment by spiffmon** [comment]
Considering this PR is on deck for us, pending wrapping our enhanced UTF-8 support, which had gotten bumped by internal priorities.  Thanks!

**Comment by gitamohr** [comment]
Thanks for this!  I tweaked it slightly to use the ARCH_CPU_ARM define we already have to be consistent with the other conditional code.  I will check this in once it passes our internal test suite and then it will show up on github in the next push.

**Pull request merged**
