### PR TITLE
[build_scripts, cmake, glf] Remove OpenEXR from default dependencies.

### PR DESCRIPTION
**Pull request by asluk**
See discussion in https://groups.google.com/d/msg/usd-interest/hmb7ZVVtscY/DmqNROd8BwAJ

### CODE REVIEW

**Comment by asluk** [comment]
Closing this while I look into some potential unit test regressions.

**Comment by asluk** [comment]
Verified that the Windows test failures I was seeing was just because I was running them over Remote Desktop. Running them locally, everything passes except for the ones that I've addressed in https://github.com/PixarAnimationStudios/USD/pull/848

**Comment by jilliene** [comment]
Filed as internal issue #USD-5794

**Comment by c64kernal** [comment]
Thanks again @asluk  -- should be merged in on the next push up.

**Pull request merged**
