### PR TITLE
APPLE: Add usdView controls to show/hide the sky dome

### PR DESCRIPTION
**Pull request by creijon**
### Description of Change(s)

With 22.11 there was the new `domeLightCameraVisibility` render setting to hide the sky dome background when the dome light was enabled.  This is really useful for displaying quality lighting in the viewport while maintaining a transparent or flat background.

This change hooks up the setting to a new menu item in usdView, under Display -> Show Dome Light Textures

### Fixes Issue(s)
- Control of skydome rendering in usdView

- [X] I have verified that all unit tests pass with the proposed changes

- [X] I have submitted a signed Contributor License Agreement

### CODE REVIEW

**Comment by sunyab** [comment]
Filed as internal issue #USD-7819

**Comment by FlorianZ** [comment]
@jonny-apple, we had our UI/UX design team take a look and they recommended moving this option to the "Display" menu and calling it "Show Dome Light Textures" instead. Would you mind updating the PR with that change? Thank you!

**Comment by creijon** [comment]
> @jonny-apple, we had our UI/UX design team take a look and they recommended moving this option to the "Display" menu and calling it "Show Dome Light Textures" instead. Would you mind updating the PR with that change? Thank you!

Certainly, I'll do that right away.

**Comment by creijon** [comment]
> > @jonny-apple, we had our UI/UX design team take a look and they recommended moving this option to the "Display" menu and calling it "Show Dome Light Textures" instead. Would you mind updating the PR with that change? Thank you!
> 
> Certainly, I'll do that right away.

Done!

**Comment by creijon** [comment]
Cleaned up the Python code to use consistent naming.

**Pull request closed without merging**
