### PR TITLE
Adding `GetAll` method to the `codegenTemplates` for multiple-apply schemas

### PR DESCRIPTION
**Pull request by robpieke**
### Description of Change(s)

Adding `GetAll` method to the `codegenTemplates` for multiple-apply schemas, both for C++ and Python.

This should enable a workflow such as:
```
from pxr import Usd

stage = Usd.Stage.CreateInMemory()
prim = stage.DefinePrim('/test')

MyMultipleApplySchema.Apply(prim, 'banana')
MyMultipleApplySchema.Apply(prim, 'apple')
MyMultipleApplySchema.Apply(prim, 'pear')

for api in MyMultipleApplySchema.GetAll(prim):
  api.GetAwesomenessAttr().Set(1.0)
```

This has been tested by rerunning `usdGenSchema` in the USD codebase and comparing the results of `UsdCollectionAPI.GetAll(prim)` to `UsdCollectionAPI.GetAllCollections(prim)` and verifying the entries in the resulting lists are the same.

### Fixes Issue(s)
#1772 

### Note

I might not yet be covered by a CLA, but that should be addressed shortly :)

### CODE REVIEW

**Comment by spiffmon** [comment]
@robpieke, could you please also rerun usdGenSchema in pxr/usd/usd to pick up the changes to UsdCollectionAPI, and also augment the doc for GetAllCollections() to to say that it is equivalent to GetAll()... and if SideFx is OK with updating some code eventually, maybe "\deprecate" GetAllCollections() ?

**Comment by robpieke** [comment]
> @robpieke, could you please also rerun usdGenSchema in pxr/usd/usd to pick up the changes to UsdCollectionAPI, and also augment the doc for GetAllCollections() to to say that it is equivalent to GetAll()... and if SideFx is OK with updating some code eventually, maybe "\deprecate" GetAllCollections() ?

Done! Thanks for the speedy feedback!

**Comment by robpieke** [comment]
> if SideFx is OK with updating some code eventually

@spiffmon just to check, was this a suggestion we could/should sweep the USD codebase and change usages of `GetAllCollections` to `GetAll`, or would you prefer that be left to your team?

**Comment by spiffmon** [comment]
@robpieke , AFAICT, Pixar has three internal uses of GetAllCollections() that we'll be on the hook to update, but otherwise the HUSD is the only other place I see it in use.  And thanks for updating UsdPhysics - I forgot that has multi-apply schemas!

**Comment by robpieke** [comment]
> the HUSD is the only other place I see it in use

@spiffmon Yeah, we have about ten usages split between C++ and Python that we'll swap over.

**Comment by jilliene** [comment]
Filed as internal issue #USD-7221

**Comment by robpieke** [comment]
Just checking to make sure this isn't waiting on me for anything :)

**Comment by spiffmon** [comment]
Hi @robpieke , no it's not.  We have a backlog of internal and external issues/PR's we're working our way through, and just haven't even gotten to this one yet.

**Comment by crevilla** [comment]
Hi @robpieke 
I was asked to review this pull request here at Pixar and I think we'd benefit from having more of the implementation of GetAll centralized as opposed to written explicitly into every multiple apply API schema.
In particular, it'd be useful to have a static protected function in UsdAPISchemaBase:
static TfTokenVector _GetMultipleApplyInstances(const UsdPrim &prim, const TfType &schemaType)
to return all the instance names matching the schema type for a prim so that the generated code only has to populate the vector of schema of objects from this list.
For the shared function's impelementation, the UsdSchemaRegistry has the static functions GetAPISchemaTypeName and GetTypeNameAndInstance to help get the type name of the schema and to parse type name and instance name from an applied schema string respectively.

**Comment by robpieke** [comment]
Hi @crevilla ... sorry it took so long to return to this, but I've taken a stab at centralising the logic as requested.

**Comment by sunyab** [comment]
This PR was just merged into the dev branch, not sure why this PR didn't auto close. Closing this out.

**Pull request closed without merging**
